steps:
  # Step 1: Install Python dependencies
  - name: 'python:3.12'
    entrypoint: 'pip'
    args: ['install', '-r', 'agent/requirements.txt', '--user']
    
  # Step 2: Deploy agent to Vertex AI Agent Engine
  - name: 'python:3.12'
    entrypoint: 'python'
    args: ['deploy_agent.py']
    env:
      - 'PYTHONUNBUFFERED=1'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1800s'  # 30 minutes