steps:
  # Step 1: Install dependencies
  - name: 'python:3.12'
    entrypoint: 'pip'
    args: ['install', '-r', 'agent/requirements.txt', 'pyyaml', '--user']
    id: 'install-deps'
  
  # ============================================================================
  # CONDITIONAL DEPLOYMENT TO DEV
  # ============================================================================
  - name: 'python:3.12'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "${_DEPLOY_TO_DEV}" = "true" ]; then
          echo "🚀 Deploying to DEV environment..."
          python deploy_agent.py
          echo "✅ DEV deployment completed"
        else
          echo "⏭️  Skipping DEV deployment"
        fi
    env:
      - 'ENVIRONMENT=dev'
      - 'PYTHONUNBUFFERED=1'
    id: 'deploy-dev'
    waitFor: ['install-deps']  # Changed from 'run-tests' to 'install-deps'
  
  # ============================================================================
  # CONDITIONAL DEPLOYMENT TO STAGING
  # ============================================================================
  - name: 'python:3.12'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "${_DEPLOY_TO_STAGING}" = "true" ]; then
          echo "🚀 Deploying to STAGING environment..."
          python deploy_agent.py
          echo "✅ STAGING deployment completed"
        else
          echo "⏭️  Skipping STAGING deployment"
        fi
    env:
      - 'ENVIRONMENT=staging'
      - 'PYTHONUNBUFFERED=1'
    id: 'deploy-staging'
    waitFor: ['install-deps']  # Changed from 'run-tests' to 'install-deps'
  
  # ============================================================================
  # CONDITIONAL DEPLOYMENT TO PRODUCTION
  # ============================================================================
  - name: 'python:3.12'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "${_DEPLOY_TO_PRODUCTION}" = "true" ]; then
          echo "🚀 Deploying to PRODUCTION environment..."
          python deploy_agent.py
          echo "✅ PRODUCTION deployment completed"
        else
          echo "⏭️  Skipping PRODUCTION deployment"
        fi
    env:
      - 'ENVIRONMENT=production'
      - 'PYTHONUNBUFFERED=1'
    id: 'deploy-production'
    waitFor: ['install-deps']  # Changed from 'run-tests' to 'install-deps'

# Default: Auto-deploy to DEV only when triggered by git push
substitutions:
  _DEPLOY_TO_DEV: 'true'
  _DEPLOY_TO_STAGING: 'false'
  _DEPLOY_TO_PRODUCTION: 'false'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '3600s'